FROM node:14-alpine AS builder
WORKDIR /usr/app
COPY . .
RUN npm install -g nx
RUN npm i -g rimraf
RUN npm i -g @nestjs/cli
RUN npm install
RUN nx build:lambda my-nest-app

FROM public.ecr.aws/lambda/nodejs:16
WORKDIR ${LAMBDA_TASK_ROOT}
COPY --from=builder /usr/app/dist/apps/my-nest-app/* ./
CMD [ "lambda.handler" ]